clear; clc

%% =====================================================================
%  MAIN_FLYBY_MULTISTRATEGY_LIGHT  --  LIGHT / EXPLORATORY VERSION
%  ---------------------------------------------------------------------
%  Purpose
%  -------
%  This script runs a reduced-cost multi-strategy beam search for a
%  propellant-free gravity-assist tour in the Mythara system. It is the
%  fast exploratory companion to the heavy search script: the same physics,
%  score model, node structure, and pruning logic are used, but the beam
%  widths, seed archive sizes, and number of time-of-flight refinements are
%  kept smaller so that candidate sequence families can be evaluated quickly.
%
%  The trajectory is represented as a chain of Lambert arcs connected by
%  zero-duration patched-conic flybys. Each search node stores:
%
%     - the body sequence visited so far;
%     - the absolute flyby epochs in years;
%     - the Lambert branch flag for each transfer;
%     - the current incoming V-infinity vector at the last body;
%     - the raw science score, the optional official score, and a rank value.
%
%  This LIGHT version is intended for fast iteration, debugging, and branch
%  discovery. It is especially useful before launching the expensive heavy
%  search, because it reveals whether a family is worth spending more CPU
%  time on. In this version the first configuration is biased toward heavy
%  bodies [9, 8, 10] in order to search for higher-score tours beyond the
%  dense low-value 5-6-7 loops.
%
%  Dynamical model
%  ---------------
%  1. Planet states are generated by KM_solver.m using bodies.mat.
%  2. Each transfer arc is solved with lambert_universal.m.
%  3. Each intermediate massive flyby must satisfy equality of the incoming
%     and outgoing V-infinity magnitudes.
%  4. The required turn angle is checked with the patched-conic model and
%     the allowed flyby altitude interval [0.1, 100] body radii.
%  5. Nyxar is massless. If used as an interior flyby, it cannot rotate the
%     V-infinity vector; the full vector must be continuous.
%  6. Each transfer is screened against the minimum heliocentric perihelion
%     distance.
%
%  Search strategy
%  ---------------
%  The script performs a beam search with optional stochastic pruning:
%
%     Stage 1: generate all valid two-body seed arcs over a first-TOF grid.
%     Stage 2: expand the seed set once before the main beam pruning.
%     Stage 3: at every depth, try all target bodies, Lambert branches, and
%              optimized time-of-flight candidates.
%     Stage 4: rank each node using raw score, score/year, remaining time,
%              realistic future potential, heavy-body coverage, and penalties
%              for slow or low-value repeated loops.
%     Stage 5: prune the beam with diversity buckets so that promising
%              branches ending at different bodies/times/V-infinity bins are
%              not all discarded.
%     Stage 6: write an archive, summary table, MAT file, and export the top
%              CSV candidates for validation.
%
%  Scoring
%  -------
%  Every node keeps two score values:
%
%     J_raw      : score without the Grand Tour multiplier.
%     J_official : score with the optional Grand Tour multiplier.
%
%  The active objective is selected per configuration with:
%
%     cfg.USE_GRAND_TOUR_BONUS = true/false
%
%  In this file the default search optimizes raw score, because the current
%  practical goal is to maximize the score validated by the web site without
%  relying on the Grand Tour bonus.
%
%  Light-version design choices
%  ----------------------------
%  Compared with the heavy version, this file uses fewer TOF grid samples,
%  fewer refined minima per expansion, smaller archives, and fewer exported
%  CSVs. The ranking function is more aggressive about discouraging repeated
%  low-value flybys and explicitly rewards repeated visits to Ashkara,
%  Varuun, and Xerion.
%
%  How to use
%  ----------
%  Put this file in the optimization folder and run:
%
%       Main_Flyby_multistrategy_LIGHT
%
%  Required files on the MATLAB path or nearby folders:
%
%       KM_solver.m
%       lambert_universal.m
%       stumpff.m
%       solution_to_csv_patched.m
%       bodies.mat
%
%  Output
%  ------
%  The script creates results_multistrategy_LIGHT/ containing:
%
%       archive_global_final.mat   : full retained archive and best node
%       archive_summary.csv        : readable summary of retained nodes
%       csv/                       : exported CSV candidates for validation
%       run_*.mat                  : result of each individual configuration
%
%  Tuning notes
%  ------------
%  For the fastest test, uncomment cfgs = cfgs(1) inside build_configs().
%  To make it faster still, reduce BEAM_WIDTH, SEED_BEAM_WIDTH, MAX_DEPTH,
%  TOF_GRID_SHORT_N, TOF_GRID_LONG_N, and N_TOP_INTERVALS.
%
%  This documented version includes the v3 bug fixes:
%     - safe candidate struct creation in refine_next_tof_multi();
%     - row-vector-safe index concatenation in prune_frontier_diverse().
%
%  =====================================================================

% Locate this script, infer the project root, and add all required folders
% to the MATLAB path. This avoids accidental use of shadowed functions.
script_dir = fileparts(mfilename('fullpath'));
[root, paths] = setup_paths(script_dir);

bodies_file = find_bodies_file(root, paths, script_dir);
load(bodies_file,'bodies')

mu = bodies.mu_star;
ys = bodies.year_sec;
if isfield(bodies,'AU')
    AU = bodies.AU;
else
    AU = 149597870.691;
end

fprintf('\nUsing:\n')
which KM_solver
which lambert_universal
which stumpff
which solution_to_csv_patched
fprintf('bodies.mat = %s\n', bodies_file)

% Build global numerical/search options and then build the list of run
% configurations. Each configuration changes the body ordering, beam width,
% TOF grid, stochastic mode, and Grand Tour option.
opts = default_opts(root, paths, bodies_file);
cfgs = build_configs(opts);

if ~isfolder(opts.OUTDIR)
    mkdir(opts.OUTDIR)
end

% Global archive accumulates good nodes from every configuration.
% best_global is always selected by J_raw, even when a configuration uses
% the Grand Tour bonus internally for ranking.
archive_global = [];
best_global = [];

fprintf('\n=== MAIN MULTISTRATEGY SEARCH ===\n')
fprintf('Output dir: %s\n', opts.OUTDIR)
fprintf('Number of configs: %d\n', numel(cfgs))

for icfg = 1:numel(cfgs)
    cfg = cfgs(icfg);
    rng(cfg.RNG_SEED);

    fprintf('\n============================================================\n')
    fprintf('RUN %02d/%02d | %s\n', icfg, numel(cfgs), cfg.NAME)
    fprintf('============================================================\n')
    fprintf('BODY_IDS = [%s]\n', sprintf('%d ', cfg.BODY_IDS))
    fprintf('MAX_DEPTH=%d | BEAM=%d | STOCH=%d | GT_BONUS=%d\n', ...
        cfg.MAX_DEPTH, cfg.BEAM_WIDTH, cfg.USE_STOCHASTIC_BEAM, cfg.USE_GRAND_TOUR_BONUS)

    res = run_one_search(cfg, opts, bodies, mu, ys, AU);

    archive_global = merge_archive(archive_global, res.archive, opts.MAX_GLOBAL_ARCHIVE);

    if isempty(best_global) || res.best.J_raw > best_global.J_raw
        best_global = res.best;
    end

    save_run_result(res, cfg, opts);

    if cfg.N_REFINE_TOP > 0 && ~isempty(res.archive)
        fprintf('\n--- local refinement on top %d nodes ---\n', cfg.N_REFINE_TOP)
        elites = take_top_unique(res.archive, cfg.N_REFINE_TOP);
        refined = [];
        for k = 1:numel(elites)
            ref = refine_sequence_times(elites(k), cfg, opts, bodies, mu, ys, AU);
            if ~isempty(ref)
                refined = append_node(refined, ref);
                if isempty(best_global) || ref.J_raw > best_global.J_raw
                    best_global = ref;
                    fprintf('REFINE NEW BEST raw=%.9f t=%.3f seq=[%s]\n', ...
                        ref.J_raw, ref.t(end), sprintf('%d ', ref.seq))
                end
            end
        end
        archive_global = merge_archive(archive_global, refined, opts.MAX_GLOBAL_ARCHIVE);
    end
end

archive_global = prune_archive_unique(archive_global, opts.MAX_GLOBAL_ARCHIVE);
archive_global = sort_nodes(archive_global, 'raw');

summary_file = fullfile(opts.OUTDIR, 'archive_summary.csv');
write_archive_summary(archive_global, summary_file, bodies)

fprintf('\n=== GLOBAL BEST RAW ===\n')
disp_best(best_global)
print_sequence_details(best_global, bodies, mu, ys)

export_top_csvs(archive_global, opts, opts.N_EXPORT_CSV)

save(fullfile(opts.OUTDIR, 'archive_global_final.mat'), ...
    'archive_global', 'best_global', 'cfgs', 'opts')

fprintf('\nDONE.\n')
fprintf('Best raw = %.9f\n', best_global.J_raw)
fprintf('Summary  = %s\n', summary_file)
fprintf('Folder   = %s\n', opts.OUTDIR)

%% =====================================================================
function opts = default_opts(root, paths, bodies_file)
%DEFAULT_OPTS Define global constants and lightweight numerical controls.
% These values are shared by all configurations. The main runtime drivers
% are TOF_GRID_SHORT_N, TOF_GRID_LONG_N, N_TOP_INTERVALS, N_TOP_TOF, and the
% per-configuration BEAM_WIDTH / SEED_BEAM_WIDTH values.

opts.ROOT = root;
opts.PATHS = paths;
opts.BODIES_FILE = bodies_file;
opts.OUTDIR = fullfile(root, 'results_multistrategy_LIGHT');

opts.MAX_TIME = 300;              % yr
opts.MAX_FLYBYS_PER_BODY = 13;

opts.DIRS = [0 1];
opts.TOF_MIN = 1.5;
opts.TOF_MAX = 160;
opts.VINFTOL = 1e-3;              % km/s = 1 mm/s search tolerance
opts.SOFT_VINFTOL_FACTOR = 3.0;   % only for candidate generation; final child is strict

opts.MIN_H_OVER_R = 0.1;
opts.MAX_H_OVER_R = 100.0;
opts.MIN_PERIHELION_AU = 0.01;
opts.DEFAULT_PERIHELION_AU = 0.05;

% Time-of-flight multi-candidate refinement.  These are intentionally much
% smaller than in the heavy script: the purpose is to test families quickly.
opts.TOF_GRID_SHORT_N = 12;
opts.TOF_GRID_LONG_N  = 10;
opts.TOF_SHORT_CUT_YR = 35;
opts.N_TOP_INTERVALS = 2;
opts.N_TOP_TOF = 1;
opts.COST_TURN_W = 1e-4;
opts.COST_TOF_W  = 2e-5;

% Diversified pruning.  One protected representative per bucket keeps the
% search broad while limiting total expansion cost.
opts.TIME_BIN_YR = 10;
opts.VINF_BIN = 1.5;
opts.KEEP_PER_BUCKET = 1;
opts.MAX_GLOBAL_ARCHIVE = 6000;
opts.N_EXPORT_CSV = 6;

% Stochastic beam parameters.  Only configurations with
% cfg.USE_STOCHASTIC_BEAM=true use these values.
opts.ELITE_FRAC = 0.40;
opts.SOFTMAX_T = 15.0;

% Ranking parameters.  HEAVY_IDS are the bodies that should be protected and
% encouraged by the heuristic rank.  LOWVALUE_IDS are penalized if repeated
% too often, especially in raw-score searches.
opts.TARGET_MEAN_TOF = 18;
opts.TARGET_RECENT_TOF = 15;
opts.REPEAT_FRAC = 1/3;
opts.MIN_INSERT_GAP = 5.0;
opts.HEAVY_IDS = [10 9 8 7];
opts.LOWVALUE_IDS = [4 5 1000];
opts.RANK_F_REF = 0.72;
opts.RANK_FUTURE_SCALE = 0.24;

% Optional local refinement.  Disabled in the default light configurations.
opts.REFINE_RESTARTS = 3;
opts.REFINE_SWEEPS = 2;
opts.REFINE_STEP_FRAC = 0.04;
opts.REFINE_MIN_STEP_YR = 0.03;

end

%% =====================================================================
function cfgs = build_configs(opts)
%BUILD_CONFIGS Create the lightweight run list.
% The first configuration is the recommended one for pushing toward higher
% raw scores: it removes Cindrel/Nyxar from the main body list and biases the
% ordering toward Varuun, Ashkara, and Xerion.  The other configurations are
% fallback exploratory searches.

base = base_cfg(opts);
cfgs = base([]);

cfgs(end+1) = make_cfg(base, 'HEAVY_FORCED_250', ...
    [9 8 10 7 6 5], false, false, ...
    [2:2:30 36:6:90 100:10:160], ...
    120, ...    % BEAM_WIDTH
    24, ...     % MAX_DEPTH
    500, ...    % SEED_BEAM_WIDTH
    303, ...
    0);

cfgs(end+1) = make_cfg(base, 'ULTRA_LIGHT_dense_raw', ...
    [9 8 7 6 5 10 4 1000], false, false, ...
    [1.5:0.5:40 42:2:80], ...
    800, ...    % BEAM_WIDTH
    60, ...     % MAX_DEPTH
    1500, ...   % SEED_BEAM_WIDTH
    101, ...
    0);

% Main quick raw search: dense early legs, with Nyxar available only if the
% configuration allows it.  This is useful for reproducing dense 5-6-7 style
% families and checking whether they can be extended with heavy bodies.
cfgs(end+1) = make_cfg(base, 'LIGHT_dense_raw', ...
    [9 8 7 6 5 10 4 1000], false, false, ...
    [2:1:28 30:3:75], 140, 30, 500, 101, 0);

% Small stochastic variant to reduce deterministic pruning loss.  It keeps
% elite nodes and samples additional nodes using a softmax rank distribution.
cfgs(end+1) = make_cfg(base, 'LIGHT_stochastic_raw', ...
    [9 8 7 6 5 10 4 1000], false, true, ...
    [2:1.5:35 40:5:90], 160, 30, 650, 202, 0);

% For fastest test only, uncomment this line:
% cfgs = cfgs(1);

end

%% =====================================================================
function cfg = base_cfg(opts)
%BASE_CFG Default configuration template copied and customized by make_cfg().

cfg.NAME = 'base';
cfg.BODY_IDS = [10 9 8 7 6 5 4 1000];
cfg.USE_GRAND_TOUR_BONUS = false;
cfg.USE_STOCHASTIC_BEAM = false;
cfg.ALLOW_NYXAR_INTERIOR_PASS = false;
cfg.ALLOW_NYXAR_TERMINAL_ONLY = true;

cfg.MAX_TIME = opts.MAX_TIME;
cfg.MAX_DEPTH = 60;
cfg.BEAM_WIDTH = 800;
cfg.SEED_BEAM_WIDTH = 2000;
cfg.SEED_PRUNE_DEPTH = 3;
cfg.TOF_FIRST_GRID = [1:0.25:20 21:1:100];
cfg.DIRS = opts.DIRS;
cfg.RNG_SEED = 1;
cfg.N_REFINE_TOP = 0;

end

%% =====================================================================
function cfg = make_cfg(base, name, body_ids, use_gt, stochastic, tof_grid, beam_width, max_depth, seed_beam, rng_seed, n_refine)
%MAKE_CFG Helper constructor for one search configuration.

cfg = base;
cfg.NAME = name;
cfg.BODY_IDS = body_ids;
cfg.USE_GRAND_TOUR_BONUS = use_gt;
cfg.USE_STOCHASTIC_BEAM = stochastic;
cfg.TOF_FIRST_GRID = tof_grid;
cfg.BEAM_WIDTH = beam_width;
cfg.MAX_DEPTH = max_depth;
cfg.SEED_BEAM_WIDTH = seed_beam;
cfg.RNG_SEED = rng_seed;
cfg.N_REFINE_TOP = n_refine;

end

%% =====================================================================
function res = run_one_search(cfg, opts, bodies, mu, ys, AU)
%RUN_ONE_SEARCH Execute one complete beam-search configuration.
% The function starts from all valid pair seeds, expands them to depth 3
% before tight pruning, then continues layer by layer until MAX_DEPTH or until
% no valid children remain.

frontier = generate_pair_seeds(cfg, opts, bodies, mu, ys, AU);

if isempty(frontier)
    warning('No initial seed found for %s.', cfg.NAME)
    res.best = [];
    res.archive = [];
    return
end

fprintf('Initial seed count before prune: %d\n', numel(frontier))
frontier = prune_frontier_diverse(frontier, cfg.SEED_BEAM_WIDTH, cfg, opts);
fprintf('Initial seed count after prune:  %d\n', numel(frontier))
print_best(frontier, 5)

archive = frontier;
[~, ib] = max([frontier.J_raw]);
best = frontier(ib);
current_depth = 2;

% Delayed pruning: expand seeds once before main pruning.
if cfg.SEED_PRUNE_DEPTH >= 3
    fprintf('\n=== SEED EXPANSION TO DEPTH 3 ===\n')
    children = expand_frontier(frontier, cfg, opts, bodies, mu, ys, AU);
    if ~isempty(children)
        archive = merge_archive(archive, children, opts.MAX_GLOBAL_ARCHIVE);
        [~, ibc] = max([children.J_raw]);
        if children(ibc).J_raw > best.J_raw
            best = children(ibc);
        end
        frontier = prune_frontier_diverse(children, cfg.BEAM_WIDTH, cfg, opts);
        current_depth = 3;
        print_best(frontier, 8)
    else
        fprintf('No depth-3 children; continue from seeds.\n')
    end
end

for depth = current_depth+1:cfg.MAX_DEPTH
    fprintf('\n=== DEPTH %d ===\n', depth)

    children = expand_frontier(frontier, cfg, opts, bodies, mu, ys, AU);

    if isempty(children)
        fprintf('No children found. Stop run.\n')
        break
    end

    archive = merge_archive(archive, children, opts.MAX_GLOBAL_ARCHIVE);

    [~, ibc] = max([children.J_raw]);
    if children(ibc).J_raw > best.J_raw
        best = children(ibc);
        fprintf('NEW BEST raw=%.9f t=%.3f seq=[%s]\n', ...
            best.J_raw, best.t(end), sprintf('%d ', best.seq))
    end

    frontier = prune_frontier_diverse(children, cfg.BEAM_WIDTH, cfg, opts);
    print_best(frontier, 8)
end

res.best = best;
res.archive = prune_archive_unique(archive, opts.MAX_GLOBAL_ARCHIVE);

fprintf('\n--- RUN BEST | %s ---\n', cfg.NAME)
disp_best(best)

end

%% =====================================================================
function frontier = generate_pair_seeds(cfg, opts, bodies, mu, ys, AU)
%GENERATE_PAIR_SEEDS Build the initial frontier from all two-body arcs.
% These are not full flyby chains yet. They provide the incoming V-infinity
% vector at the second body, which is required to close the next flyby.

frontier = [];
fail_count = 0;
max_fail_print = 20;

for a = cfg.BODY_IDS
    for b = cfg.BODY_IDS
        if b == a
            continue
        end

        for tof = cfg.TOF_FIRST_GRID
            t1 = 0;
            t2 = tof;

            if t2 > cfg.MAX_TIME
                continue
            end

            for dir = cfg.DIRS
                try
                    [vdep, varr, ~, vp2, r1, ~] = leg_vel(a, b, t1, t2, dir, bodies, mu, ys);

                    rp_AU = perihelion_AU(r1, vdep, mu, AU);
                    if rp_AU < opts.MIN_PERIHELION_AU
                        continue
                    end

                    arr_vinf_last = varr(:) - vp2(:);
                    node = pack_node([a b], [t1 t2], dir, arr_vinf_last, NaN, NaN, rp_AU);
                    node = update_node_scores_and_rank(node, cfg, opts, bodies, mu, ys);
                    frontier = append_node(frontier, node);

                catch ME
                    fail_count = fail_count + 1;
                    if fail_count <= max_fail_print
                        fprintf('SEED FAIL %d -> %d | TOF %.2f | dir %d | %s\n', ...
                            a, b, tof, dir, ME.message)
                    end
                end
            end
        end
    end
end

end

%% =====================================================================
function children = expand_frontier(frontier, cfg, opts, bodies, mu, ys, AU)
%EXPAND_FRONTIER Expand every parent node by one additional flyby.
% For each parent, every target body and Lambert direction is tested. The
% time of flight is not fixed: refine_next_tof_multi() searches for TOFs that
% close the V-infinity magnitude at the current flyby.

children = [];

for ip = 1:numel(frontier)
    parent = frontier(ip);
    last_id = parent.seq(end);

    for target = cfg.BODY_IDS
        if target == last_id
            continue
        end

        if count_body(parent.seq, target) >= opts.MAX_FLYBYS_PER_BODY
            continue
        end

        if target == 1000 && cfg.ALLOW_NYXAR_TERMINAL_ONLY && ~cfg.ALLOW_NYXAR_INTERIOR_PASS
            % In raw runs Nyxar is not useful as an interior flyby.
            % It can still appear only if the run ends there; beam cannot know that now.
            continue
        end

        for dir = cfg.DIRS
            cand = refine_next_tof_multi(parent, target, dir, cfg, opts, bodies, mu, ys, AU);

            for ic = 1:numel(cand)
                tof = cand(ic).tof;
                t1 = parent.t(end);
                t2 = t1 + tof;

                if t2 > cfg.MAX_TIME
                    continue
                end

                if ~repeated_timing_ok(parent.seq, parent.t, target, t2, bodies, opts)
                    continue
                end

                try
                    [vdep, varr, vp1, vp2, r1, ~] = leg_vel(last_id, target, t1, t2, dir, bodies, mu, ys);

                    rp_AU = perihelion_AU(r1, vdep, mu, AU);
                    if rp_AU < opts.MIN_PERIHELION_AU
                        continue
                    end

                    vinf_in  = parent.arr_vinf_last(:);
                    vinf_out = vdep(:) - vp1(:);

                    [okfly, hR, delta_deg] = flyby_ok(last_id, vinf_in, vinf_out, bodies, opts, cfg);
                    if ~okfly
                        continue
                    end

                    arr_vinf_last = varr(:) - vp2(:);
                    child = pack_node([parent.seq target], [parent.t t2], [parent.dirs dir], ...
                        arr_vinf_last, hR, delta_deg, rp_AU);
                    child = update_node_scores_and_rank(child, cfg, opts, bodies, mu, ys);

                    children = append_node(children, child);

                catch
                    % Keep the search clean. Bad Lambert arcs die here.
                end
            end
        end
    end
end

end

%% =====================================================================
function cand = refine_next_tof_multi(parent, target, dir, cfg, opts, bodies, mu, ys, AU)
%REFINE_NEXT_TOF_MULTI Find one or more promising TOFs for the next leg.
% The method samples a coarse TOF grid, detects local minima of the flyby
% closure cost, then refines each selected interval with fminbnd(). This is
% more robust than running fminbnd() on one large interval.

cand = empty_candidate();

remaining = cfg.MAX_TIME - parent.t(end);
tof_hi = min(opts.TOF_MAX, remaining);
tof_lo = opts.TOF_MIN;

if tof_hi <= tof_lo
    return
end

cut = min(opts.TOF_SHORT_CUT_YR, tof_hi);
g1 = linspace(tof_lo, cut, opts.TOF_GRID_SHORT_N);
if tof_hi > cut + 1e-9
    g2 = linspace(cut, tof_hi, opts.TOF_GRID_LONG_N);
    grid = unique([g1 g2]);
else
    grid = unique(g1);
end

cost = inf(size(grid));
meta = repmat(empty_meta(), size(grid));

for k = 1:numel(grid)
    [cost(k), meta(k)] = closure_cost_at_tof(parent, target, dir, grid(k), cfg, opts, bodies, mu, ys, AU);
end

finite_idx = find(isfinite(cost));
if isempty(finite_idx)
    return
end

idxs = pick_best_grid_indices(cost, opts.N_TOP_INTERVALS);

out = empty_candidate();
for ii = 1:numel(idxs)
    idx = idxs(ii);
    lo = grid(max(1, idx-1));
    hi = grid(min(numel(grid), idx+1));

    if hi <= lo
        continue
    end

    try
        f = @(tof) closure_cost_scalar(parent, target, dir, tof, cfg, opts, bodies, mu, ys, AU);
        [tof_star, cost_star] = fminbnd(f, lo, hi, optimset('TolX', 1e-8, 'Display', 'off'));
    catch
        tof_star = grid(idx);
        cost_star = cost(idx);
    end

    [~, met] = closure_cost_at_tof(parent, target, dir, tof_star, cfg, opts, bodies, mu, ys, AU);

    if met.miss_mag <= opts.VINFTOL * opts.SOFT_VINFTOL_FACTOR
        c = make_candidate(tof_star, cost_star, met);
        out = append_candidate(out, c);
    end
end

if isempty(out)
    return
end

% remove near-duplicates by TOF
out = unique_candidates_by_tof(out, 1e-5);
[~, ord] = sort([out.cost], 'ascend');
out = out(ord);
cand = out(1:min(opts.N_TOP_TOF, numel(out)));

end

%% =====================================================================
function y = closure_cost_scalar(parent, target, dir, tof, cfg, opts, bodies, mu, ys, AU)
[y, ~] = closure_cost_at_tof(parent, target, dir, tof, cfg, opts, bodies, mu, ys, AU);
end

%% =====================================================================
function [cost, met] = closure_cost_at_tof(parent, target, dir, tof, cfg, opts, bodies, mu, ys, AU)
%CLOSURE_COST_AT_TOF Objective used during TOF refinement.
% Main term: absolute mismatch between outgoing and incoming V-infinity
% magnitudes at the flyby body. Soft terms penalize impossible turn angles and
% very long TOFs, guiding the optimizer toward useful physical closures.

met = empty_meta();
cost = Inf;

try
    t1 = parent.t(end);
    t2 = t1 + tof;

    if t2 > cfg.MAX_TIME || tof <= 0
        return
    end

    [vdep, ~, vp1, ~, r1, ~] = leg_vel(parent.seq(end), target, t1, t2, dir, bodies, mu, ys);

    rp_AU = perihelion_AU(r1, vdep, mu, AU);
    if rp_AU < opts.MIN_PERIHELION_AU
        return
    end

    vinf_in  = parent.arr_vinf_last(:);
    vinf_out = vdep(:) - vp1(:);

    nin = norm(vinf_in);
    nout = norm(vinf_out);
    if nin <= 0 || nout <= 0
        return
    end

    miss_mag = abs(nout - nin);
    delta_deg = turn_angle_deg(vinf_in, vinf_out);

    [turn_violation_deg, ~, ~] = turn_violation(parent.seq(end), vinf_in, vinf_out, bodies, opts, cfg);

    % Main term remains Vinf magnitude closure.
    % Small soft penalties guide fminbnd toward physically useful roots.
    cost = miss_mag ...
         + opts.COST_TURN_W * turn_violation_deg^2 ...
         + opts.COST_TOF_W  * max(0, tof - opts.TARGET_RECENT_TOF);

    met.miss_mag = miss_mag;
    met.delta_deg = delta_deg;
    met.turn_violation_deg = turn_violation_deg;
    met.rp_AU = rp_AU;

    if ~isfinite(cost)
        cost = Inf;
    end
catch
    cost = Inf;
end

end

%% =====================================================================
function idxs = pick_best_grid_indices(cost, N)

idxs = [];
finite_idx = find(isfinite(cost));
if isempty(finite_idx)
    return
end

% local minima first
for k = finite_idx(:).'
    left_ok  = (k == 1) || cost(k) <= cost(k-1);
    right_ok = (k == numel(cost)) || cost(k) <= cost(k+1);
    if left_ok && right_ok
        idxs(end+1) = k; %#ok<AGROW>
    end
end

if isempty(idxs)
    [~, ord] = sort(cost(finite_idx), 'ascend');
    idxs = finite_idx(ord(1:min(N, numel(ord))));
else
    [~, ord] = sort(cost(idxs), 'ascend');
    idxs = idxs(ord(1:min(N, numel(ord))));
end

end

%% =====================================================================
function [ok, h_over_R, delta_deg] = flyby_ok(id, vinf_in, vinf_out, bodies, opts, cfg)
%FLYBY_OK Strict patched-conic flyby validation.
% Checks V-infinity magnitude equality, required turn angle, and pericenter
% altitude. For a massless Nyxar flyby, vector continuity is required.

ok = false;
h_over_R = NaN;
delta_deg = NaN;

b = bodies.(sprintf('id_%d', id));
vin = norm(vinf_in);
vout = norm(vinf_out);

if vin <= 0 || vout <= 0
    return
end

if abs(vin - vout) > opts.VINFTOL
    return
end

if b.mu <= 0 || b.radius <= 0
    if cfg.ALLOW_NYXAR_INTERIOR_PASS && id == 1000
        dir_err = norm(vinf_out(:) - vinf_in(:));
        ok = dir_err <= opts.VINFTOL;
        h_over_R = Inf;
        delta_deg = 0;
    end
    return
end

c = dot(vinf_in, vinf_out)/(vin*vout);
c = max(-1, min(1, c));
delta = acos(c);
delta_deg = rad2deg(delta);

if delta < 1e-12
    return
end

rp = b.mu/vin^2 * (1/sin(delta/2) - 1);
h_over_R = rp/b.radius - 1;

ok = isfinite(h_over_R) && ...
     h_over_R >= opts.MIN_H_OVER_R && ...
     h_over_R <= opts.MAX_H_OVER_R;

end

%% =====================================================================
function [viol_deg, delta_min_deg, delta_max_deg] = turn_violation(id, vinf_in, vinf_out, bodies, opts, cfg)

viol_deg = 0;
delta_min_deg = 0;
delta_max_deg = 180;

b = bodies.(sprintf('id_%d', id));

if b.mu <= 0 || b.radius <= 0
    if cfg.ALLOW_NYXAR_INTERIOR_PASS && id == 1000
        viol_deg = turn_angle_deg(vinf_in, vinf_out);
        delta_min_deg = 0;
        delta_max_deg = 0;
    end
    return
end

vin = 0.5*(norm(vinf_in) + norm(vinf_out));
if vin <= 0
    viol_deg = Inf;
    return
end

rp_min = b.radius * (1 + opts.MIN_H_OVER_R);
rp_max = b.radius * (1 + opts.MAX_H_OVER_R);

delta_max = 2*asin(1/(1 + rp_min*vin^2/b.mu));
delta_min = 2*asin(1/(1 + rp_max*vin^2/b.mu));

delta_min_deg = rad2deg(delta_min);
delta_max_deg = rad2deg(delta_max);
delta_req_deg = turn_angle_deg(vinf_in, vinf_out);

if delta_req_deg < delta_min_deg
    viol_deg = delta_min_deg - delta_req_deg;
elseif delta_req_deg > delta_max_deg
    viol_deg = delta_req_deg - delta_max_deg;
else
    viol_deg = 0;
end

end

%% =====================================================================
function node = update_node_scores_and_rank(node, cfg, opts, bodies, mu, ys)

[J_raw, J_official, info] = score_node_dual(node, cfg, bodies, mu, ys);
node.J_raw = J_raw;
node.J_official = J_official;
node.score_info = info;

if cfg.USE_GRAND_TOUR_BONUS
    node.J = node.J_official;
else
    node.J = node.J_raw;
end

node.rank = rank_node_smart(node, cfg, opts, bodies);
node.score_rate = node.J_raw / max(node.t(end), 1e-9);

end

%% =====================================================================
function [J_raw, J_official, info] = score_node_dual(node, cfg, bodies, mu, ys)
%SCORE_NODE_DUAL Compute raw and optional official scores for one node.
% J_raw ignores the Grand Tour bonus. J_official applies the 1.2 multiplier
% only if the configuration enables it and all bodies are present.

seq = node.seq;
t = node.t;
dirs = node.dirs;

n = numel(seq);
nleg = n - 1;

R = zeros(n,3);
VP = zeros(n,3);

for k = 1:n
    s = KM_solver(t(k)*ys, bodies.(sprintf('id_%d', seq(k))));
    R(k,:)  = s(1:3).';
    VP(k,:) = s(4:6).';
end

vdep = zeros(nleg,3);
varr = zeros(nleg,3);

for leg = 1:nleg
    [vd, va] = leg_vel(seq(leg), seq(leg+1), t(leg), t(leg+1), dirs(leg), bodies, mu, ys);
    vdep(leg,:) = vd(:).';
    varr(leg,:) = va(:).';
end

vinf = zeros(1,n);
for k = 1:n
    if k == 1
        vinf(k) = norm(vdep(1,:) - VP(k,:));
    elseif k <= nleg
        vin = norm(varr(k-1,:) - VP(k,:));
        vou = norm(vdep(k,:)   - VP(k,:));
        vinf(k) = 0.5*(vin + vou);
    else
        vinf(k) = norm(varr(k-1,:) - VP(k,:));
    end
end

rhat = R ./ vecnorm(R,2,2);
all_ids = [4 5 6 7 8 9 10 1000];

J_raw = 0;
by_body = struct();

for id = all_ids
    idx = find(seq == id);
    if isempty(idx)
        continue
    end

    idx = idx(1:min(13,numel(idx)));
    b = bodies.(sprintf('id_%d', id));
    w = b.weight;

    prev_dirs = [];
    contrib = 0;

    for ii = 1:numel(idx)
        k = idx(ii);
        V = vinf(k);

        F = 0.2 + exp(-V/13)/(1 + exp(-5*(V - 1.5)));

        if ii == 1
            S = 1.0;
        else
            dots = prev_dirs * rhat(k,:)';
            dots = max(-1,min(1,dots));
            ang = acosd(dots);
            S = 0.1 + 0.9/(1 + 10*sum(exp(-(ang.^2)/50)));
        end

        dJ = w*S*F;
        contrib = contrib + dJ;
        J_raw = J_raw + dJ;
        prev_dirs = [prev_dirs; rhat(k,:)]; %#ok<AGROW>
    end

    by_body.(sprintf('id_%d', id)) = contrib;
end

visited = unique(seq);
grand_tour_hit = all(ismember(all_ids, visited));
bonus = 1.0;
if cfg.USE_GRAND_TOUR_BONUS && grand_tour_hit
    bonus = 1.2;
end
J_official = J_raw * bonus;

info.vinf = vinf;
info.grand_tour_hit = grand_tour_hit;
info.bonus = bonus;
info.by_body = by_body;

end

%% =====================================================================
function R = rank_node_smart(node, cfg, opts, bodies)
%RANK_NODE_SMART Heuristic score used for beam pruning.
% The rank is not the final objective.  It estimates which partial tours are
% worth keeping by combining current raw score, score density, remaining-time
% potential, body diversity, and explicit incentives for repeated high-value
% bodies.  This light version penalizes repeated low-value loops more
% aggressively than the original rank because the previous search tended to
% collapse into many Aurelios/Tharos/Glacior repetitions.

J = node.J_raw;
t_now = node.t(end);
n_vis = numel(node.seq);

yrs_left = max(0, cfg.MAX_TIME - t_now);
slots_left = max(0, cfg.MAX_DEPTH - n_vis);

if yrs_left <= 0 || slots_left <= 0
    R = J - 1000*max(0,t_now-cfg.MAX_TIME);
    return
end

score_rate = J / max(t_now, 1e-6);

if n_vis >= 2
    dt = diff(node.t);
    avg_tof = mean(dt);
    recent_tof = mean(dt(max(1,end-2):end));
else
    avg_tof = opts.TARGET_MEAN_TOF;
    recent_tof = opts.TARGET_MEAN_TOF;
end

% Penalize paths that spend too much time while accumulating too few flybys.
target_vis_now = 1 + floor(t_now / opts.TARGET_MEAN_TOF);
lag = max(0, target_vis_now - n_vis);

% Future score potential must be time-realistic.  Do not assume that all
% remaining depth slots can actually be filled within the remaining years.
slots_by_time = max(0, floor(yrs_left / max(5, opts.TARGET_RECENT_TOF)) + 1);
slots_realistic = min(slots_left, slots_by_time);

future_gains = [];
for id = cfg.BODY_IDS
    n_used = sum(node.seq == id);
    n_left_rule = max(0, opts.MAX_FLYBYS_PER_BODY - n_used);
    if n_left_rule <= 0
        continue
    end

    b = bodies.(sprintf('id_%d', id));
    w = b.weight;
    T = b.period_year;

    gap = max(opts.MIN_INSERT_GAP, opts.REPEAT_FRAC*T);
    if n_used == 0
        n_time_real = 1 + floor(max(0, yrs_left - opts.MIN_INSERT_GAP)/gap);
        season0 = 1.00;
    elseif n_used == 1
        n_time_real = floor(yrs_left/gap);
        season0 = 0.90;
    elseif n_used == 2
        n_time_real = floor(yrs_left/gap);
        season0 = 0.72;
    else
        n_time_real = floor(yrs_left/gap);
        season0 = max(0.35, 0.72*0.85^(n_used-2));
    end

    n_real = min([n_left_rule, n_time_real, slots_realistic]);
    if n_real <= 0
        continue
    end

    base = w * opts.RANK_F_REF;
    if ismember(id, opts.HEAVY_IDS)
        base = 1.10*base;
    end
    if ismember(id, opts.LOWVALUE_IDS)
        base = 0.70*base;
    end

    for k = 1:n_real
        future_gains(end+1) = base * max(0.25, season0*0.88^(k-1)); %#ok<AGROW>
    end
end

future_gains = sort(future_gains,'descend');
future_bonus = opts.RANK_FUTURE_SCALE * sum(future_gains(1:min(slots_realistic,numel(future_gains))));

heavy_unique = numel(intersect(unique(node.seq), opts.HEAVY_IDS));
all_unique = numel(unique(node.seq));

slow_pen   = 2.0 * max(0, avg_tof    - opts.TARGET_MEAN_TOF)^2;
recent_pen = 1.5 * max(0, recent_tof - opts.TARGET_RECENT_TOF)^2;

% Stronger low-value penalties for the 250-point search attempt.
pen_low_4 = 20.0 * sum(node.seq == 4);
pen_low_5 = 4.0  * max(0, sum(node.seq == 5) - 2);
pen_low_6 = 2.0  * max(0, sum(node.seq == 6) - 5);
pen_low_7 = 1.0  * max(0, sum(node.seq == 7) - 6);
pen_nyxar = 5.0 * sum(node.seq == 1000) * (~cfg.USE_GRAND_TOUR_BONUS);

late_pen = 30 * (t_now / cfg.MAX_TIME)^4;
lag_pen  = 4.5 * lag^2;

% Explicitly reward repeated visits to high-value bodies.  This steers the
% beam away from low-value dense loops and toward Ashkara/Varuun/Xerion.
n8  = sum(node.seq == 8);
n9  = sum(node.seq == 9);
n10 = sum(node.seq == 10);

heavy_count_bonus = ...
    5.0  * min(n8,4) + ...
    9.0  * min(n9,4) + ...
    12.0 * min(n10,3);

R = J ...
  + 18 * score_rate ...
  + future_bonus ...
  + heavy_count_bonus ...
  + 2.5 * heavy_unique ...
  + 0.8 * all_unique ...
  - lag_pen ...
  - slow_pen ...
  - recent_pen ...
  - pen_low_4 ...
  - pen_low_5 ...
  - pen_low_6 ...
  - pen_low_7 ...
  - pen_nyxar ...
  - late_pen;

end

%% =====================================================================
function out = prune_frontier_diverse(nodes, N, cfg, opts)
%PRUNE_FRONTIER_DIVERSE Keep the beam width under control without collapsing
% to one repeated family. Nodes are sorted by rank, but bucket protection keeps
% representatives with different last bodies, time bins, V-infinity bins, and
% heavy-body coverage.

if isempty(nodes)
    out = nodes;
    return
end

nodes = sort_nodes(nodes, 'rank');
N = min(N, numel(nodes));

% Bucket protection: last body + time + Vinf + heavy coverage.
keys = cell(1,numel(nodes));
for i = 1:numel(nodes)
    last = nodes(i).seq(end);
    tbin = floor(nodes(i).t(end) / opts.TIME_BIN_YR);
    vbin = floor(norm(nodes(i).arr_vinf_last) / opts.VINF_BIN);
    hcnt = sum(ismember(nodes(i).seq, [8 9 10]));
    hcnt = min(hcnt, 6);
    keys{i} = sprintf('%d_%d_%d_%d', last, tbin, vbin, hcnt);
end

[uk,~,ic] = unique(keys);
keep_idx = zeros(1,0);

for k = 1:numel(uk)
    idx = find(ic == k);
    idx = idx(:).';
    [~, loc_ord] = sort([nodes(idx).rank], 'descend');
    idx = idx(loc_ord);
    nk = min(opts.KEEP_PER_BUCKET, numel(idx));
    keep_idx = [keep_idx idx(1:nk)]; %#ok<AGROW>
end

keep_idx = unique(keep_idx(:).', 'stable');

if numel(keep_idx) > N
    [~, ord] = sort([nodes(keep_idx).rank], 'descend');
    keep_idx = keep_idx(ord(1:N));
    out = nodes(keep_idx);
    return
end

all_idx = 1:numel(nodes);
rest_idx = setdiff(all_idx, keep_idx, 'stable');
rest_idx = rest_idx(:).';

if cfg.USE_STOCHASTIC_BEAM && ~isempty(rest_idx)
    n_left = N - numel(keep_idx);
    n_elite = min(n_left, max(0, round(opts.ELITE_FRAC * N) - numel(keep_idx)));

    elite_rest = rest_idx(1:min(n_elite, numel(rest_idx)));
        elite_rest = elite_rest(:).';
        pool = setdiff(rest_idx, elite_rest, 'stable');
        pool = pool(:).';

    n_sample = N - numel(keep_idx) - numel(elite_rest);
    if n_sample > 0 && ~isempty(pool)
        ranks = [nodes(pool).rank];
        p = exp((ranks - max(ranks)) / opts.SOFTMAX_T);
        p = p / sum(p);
        pick_local = weighted_sample_no_replace(p, min(n_sample, numel(pool)));
            sampled = pool(pick_local);
            sampled = sampled(:).';
    else
            sampled = zeros(1,0);
    end

    final_idx = [keep_idx(:).' elite_rest(:).' sampled(:).'];
else
    final_idx = [keep_idx(:).' rest_idx(:).'];
end

final_idx = unique(final_idx(:).', 'stable');
final_idx = final_idx(1:min(N,numel(final_idx)));
out = nodes(final_idx);

end

%% =====================================================================
function pick = weighted_sample_no_replace(p, n)

pick = zeros(1,n);
avail = 1:numel(p);
w = p(:).';

for k = 1:n
    w = w / sum(w);
    r = rand;
    c = cumsum(w);
    j = find(r <= c, 1, 'first');
    pick(k) = avail(j);
    avail(j) = [];
    w(j) = [];
    if isempty(avail)
        pick = pick(1:k);
        return
    end
end

end

%% =====================================================================
function ref_best = refine_sequence_times(node, cfg, opts, bodies, mu, ys, AU)
%REFINE_SEQUENCE_TIMES Local continuous refinement of a fixed sequence.
% This does not change the body order or Lambert directions. It perturbs the
% leg durations and keeps changes only if the fully validated node improves.

ref_best = node;
dt0 = diff(node.t);

if isempty(dt0) || numel(dt0) ~= numel(node.dirs)
    return
end

for rr = 1:opts.REFINE_RESTARTS
    if rr == 1
        dt = dt0;
    else
        dt = dt0 .* (1 + opts.REFINE_STEP_FRAC*randn(size(dt0)));
        dt = max(opts.TOF_MIN, dt);
        if sum(dt) > cfg.MAX_TIME
            dt = dt * (0.995*cfg.MAX_TIME/sum(dt));
        end
    end

    cand = try_build_node_from_times(node.seq, [0 cumsum(dt)], node.dirs, cfg, opts, bodies, mu, ys, AU);
    if isempty(cand)
        continue
    end

    step = max(opts.REFINE_MIN_STEP_YR, opts.REFINE_STEP_FRAC*dt);

    for sweep = 1:opts.REFINE_SWEEPS
        improved = false;
        for j = 1:numel(dt)
            trials = [dt(j)-step(j), dt(j)+step(j)];
            for tv = trials
                if tv < opts.TOF_MIN
                    continue
                end
                dt_try = dt;
                dt_try(j) = tv;
                if sum(dt_try) > cfg.MAX_TIME
                    continue
                end
                cand_try = try_build_node_from_times(node.seq, [0 cumsum(dt_try)], node.dirs, cfg, opts, bodies, mu, ys, AU);
                if ~isempty(cand_try) && cand_try.J_raw > cand.J_raw
                    cand = cand_try;
                    dt = dt_try;
                    improved = true;
                end
            end
        end
        step = 0.5*step;
        if ~improved
            % keep shrinking step
        end
    end

    if cand.J_raw > ref_best.J_raw
        ref_best = cand;
    end
end

end

%% =====================================================================
function node = try_build_node_from_times(seq, t, dirs, cfg, opts, bodies, mu, ys, AU)
%TRY_BUILD_NODE_FROM_TIMES Rebuild and validate a full node from fixed times.
% Used by the local refinement step to ensure that every flyby remains
% dynamically consistent after timing perturbations.

node = [];

if any(diff(t) <= 0) || t(end) > cfg.MAX_TIME
    return
end

n = numel(seq);
if numel(dirs) ~= n-1
    return
end

% Check repeated timing.
for k = 2:n
    if ~repeated_timing_ok(seq(1:k-1), t(1:k-1), seq(k), t(k), bodies, opts)
        return
    end
end

arr_vinf_last = [];
hR_last = NaN;
delta_last = NaN;
rp_AU_last = NaN;

% First leg.
try
    [~, varr, ~, vp2, r1, ~] = leg_vel(seq(1), seq(2), t(1), t(2), dirs(1), bodies, mu, ys);
    rp_AU = perihelion_AU(r1, varr, mu, AU); %#ok<NASGU>
catch
    return
end

% Full leg/flyby validation.
for leg = 1:n-1
    try
        [vdep, varr, vp1, vp2, r1, ~] = leg_vel(seq(leg), seq(leg+1), t(leg), t(leg+1), dirs(leg), bodies, mu, ys);
    catch
        return
    end

    rp_AU_leg = perihelion_AU(r1, vdep, mu, AU);
    if rp_AU_leg < opts.MIN_PERIHELION_AU
        return
    end

    if leg >= 2
        % Validate flyby at seq(leg).
        [~, varr_prev, ~, vp_here, ~, ~] = leg_vel(seq(leg-1), seq(leg), t(leg-1), t(leg), dirs(leg-1), bodies, mu, ys);
        vinf_in = varr_prev(:) - vp_here(:);
        vinf_out = vdep(:) - vp1(:);
        [okfly, hR_last, delta_last] = flyby_ok(seq(leg), vinf_in, vinf_out, bodies, opts, cfg);
        if ~okfly
            return
        end
    end

    arr_vinf_last = varr(:) - vp2(:);
    rp_AU_last = rp_AU_leg;
end

node = pack_node(seq, t, dirs, arr_vinf_last, hR_last, delta_last, rp_AU_last);
node = update_node_scores_and_rank(node, cfg, opts, bodies, mu, ys);

end

%% =====================================================================
function [vdep, varr, vp1, vp2, r1, r2] = leg_vel(id1, id2, t1, t2, dir, bodies, mu, ys)
%LEG_VEL Convenience wrapper around ephemerides + Lambert solver.
% Returns departure/arrival spacecraft velocities and body velocities at both
% event times, all as column vectors.

s1 = KM_solver(t1*ys, bodies.(sprintf('id_%d', id1)));
s2 = KM_solver(t2*ys, bodies.(sprintf('id_%d', id2)));

r1 = s1(1:3);
r2 = s2(1:3);
vp1 = s1(4:6);
vp2 = s2(4:6);

[vdep, varr] = lambert_universal(mu, t1*ys, r1, t2*ys, r2, dir);

vdep = real(vdep(:));
varr = real(varr(:));
vp1  = vp1(:);
vp2  = vp2(:);
r1   = r1(:);
r2   = r2(:);

if any(~isfinite(vdep)) || any(~isfinite(varr))
    error('Lambert returned non-finite velocity')
end

end

%% =====================================================================
function rp_AU = perihelion_AU(r, v, mu, AU)
%PERIHELION_AU Estimate the heliocentric perihelion radius of a Lambert arc.
% Used as a fast screening constraint before accepting a candidate leg.

r = r(:);
v = v(:);

h = cross(r,v);
h2 = dot(h,h);

evec = cross(v,h)/mu - r/norm(r);
e = norm(evec);

p = h2/mu;

if e < 1e-12
    rp = p;
else
    rp = p/(1+e);
end

rp_AU = rp/AU;

if ~isfinite(rp_AU) || rp_AU <= 0
    rp_AU = Inf;
end

end

%% =====================================================================
function ok = repeated_timing_ok(seq, t, target, t_new, bodies, opts)
%REPEATED_TIMING_OK Enforce the minimum interval for repeated flybys.
% If the same target was visited before, the new visit must occur at least
% one third of that body's orbital period later.

ok = true;
idx = find(seq == target, 1, 'last');
if isempty(idx)
    return
end

Tbody = bodies.(sprintf('id_%d',target)).period_year;
min_gap = opts.REPEAT_FRAC * Tbody;

if t_new - t(idx) < min_gap
    ok = false;
end

end

%% =====================================================================
function n = count_body(seq, id)
n = sum(seq == id);
end

%% =====================================================================
function node = pack_node(seq, t, dirs, arr_vinf_last, hR_last, delta_last, rp_AU_last)

node = struct();
node.seq = seq;
node.t = t;
node.dirs = dirs;
node.arr_vinf_last = arr_vinf_last(:);
node.J = NaN;
node.J_raw = NaN;
node.J_official = NaN;
node.rank = NaN;
node.score_rate = NaN;
node.hR_last = hR_last;
node.delta_last = delta_last;
node.rp_AU_last = rp_AU_last;
node.ok = true;
node.score_info = struct();

end

%% =====================================================================
function out = append_node(out, node)
if isempty(out)
    out = node;
else
    out(end+1) = node; %#ok<AGROW>
end
end


%% =====================================================================
function c = make_candidate(tof, cost, met)
c = struct();
c.tof = tof;
c.cost = cost;
c.miss_mag = met.miss_mag;
c.delta_deg = met.delta_deg;
c.turn_violation_deg = met.turn_violation_deg;
c.rp_AU = met.rp_AU;
end

%% =====================================================================
function c = empty_candidate()
c = struct('tof', {}, 'cost', {}, 'miss_mag', {}, 'delta_deg', {}, ...
           'turn_violation_deg', {}, 'rp_AU', {});
end

%% =====================================================================
function c = append_candidate(c, item)
if isempty(c)
    c = item;
else
    c(end+1) = item; %#ok<AGROW>
end
end

%% =====================================================================
function m = empty_meta()
m = struct();
m.miss_mag = Inf;
m.delta_deg = NaN;
m.turn_violation_deg = Inf;
m.rp_AU = Inf;
end

%% =====================================================================
function out = unique_candidates_by_tof(cand, tol)

out = empty_candidate();
for i = 1:numel(cand)
    duplicate = false;
    for j = 1:numel(out)
        if abs(cand(i).tof - out(j).tof) < tol
            duplicate = true;
            if cand(i).cost < out(j).cost
                out(j) = cand(i);
            end
            break
        end
    end
    if ~duplicate
        out = append_candidate(out, cand(i));
    end
end

end

%% =====================================================================
function nodes = sort_nodes(nodes, mode)

if isempty(nodes)
    return
end

switch lower(mode)
    case 'rank'
        q = [nodes.rank];
    case 'raw'
        q = [nodes.J_raw];
    case 'official'
        q = [nodes.J_official];
    otherwise
        q = [nodes.J];
end

[~, idx] = sort(q, 'descend');
nodes = nodes(idx);

end

%% =====================================================================
function archive = merge_archive(archive, new_nodes, maxN)

if isempty(new_nodes)
    return
end

if isempty(archive)
    archive = new_nodes;
else
    archive = [archive new_nodes]; %#ok<AGROW>
end

archive = prune_archive_unique(archive, maxN);

end

%% =====================================================================
function archive = prune_archive_unique(archive, maxN)

if isempty(archive)
    return
end

archive = sort_nodes(archive, 'raw');
seen = containers.Map('KeyType','char','ValueType','logical');
keep = false(1,numel(archive));

for i = 1:numel(archive)
    key = node_signature(archive(i));
    if ~isKey(seen, key)
        seen(key) = true;
        keep(i) = true;
    end
end

archive = archive(keep);
archive = archive(1:min(maxN,numel(archive)));

end

%% =====================================================================
function key = node_signature(node)
% Include sequence + rounded times + dirs. This avoids duplicate clones but
% still keeps useful timing variants.
seq_s = sprintf('%d-', node.seq);
t_s = sprintf('%.3f-', node.t);
d_s = sprintf('%d-', node.dirs);
key = [seq_s '|' t_s '|' d_s];
end

%% =====================================================================
function elites = take_top_unique(archive, N)

archive = prune_archive_unique(archive, max(5*N, N));
archive = sort_nodes(archive, 'raw');
elites = archive(1:min(N,numel(archive)));

end

%% =====================================================================
function save_run_result(res, cfg, opts)

if isempty(res.best)
    return
end

safe = matlab.lang.makeValidName(cfg.NAME);
matfile = fullfile(opts.OUTDIR, sprintf('run_%s.mat', safe));
save(matfile, 'res', 'cfg')

fprintf('Saved run result: %s\n', matfile)

end

%% =====================================================================
function write_archive_summary(archive, filename, bodies)

fid = fopen(filename, 'w');
if fid < 0
    warning('Could not write archive summary: %s', filename)
    return
end

fprintf(fid, 'rank,J_raw,J_official,t_end,nflybys,score_rate,sequence,names,times,dirs\n');

for i = 1:numel(archive)
    node = archive(i);
    names = cell(1,numel(node.seq));
    for k = 1:numel(node.seq)
        names{k} = body_label(node.seq(k), bodies);
    end

    seq_s = strtrim(sprintf('%d ', node.seq));
    names_s = strjoin(names, '->');
    t_s = strtrim(sprintf('%.6f ', node.t));
    d_s = strtrim(sprintf('%d ', node.dirs));

    fprintf(fid, '%d,%.12f,%.12f,%.9f,%d,%.12f,"%s","%s","%s","%s"\n', ...
        i, node.J_raw, node.J_official, node.t(end), numel(node.seq), ...
        node.J_raw/max(node.t(end),1e-9), seq_s, names_s, t_s, d_s);
end

fclose(fid);

end

%% =====================================================================
function export_top_csvs(archive, opts, N)
%EXPORT_TOP_CSVS Convert the best archived nodes to web-submission CSV files.
% The actual file formatting and any calibrated position patching are handled
% by solution_to_csv_patched().

if isempty(archive)
    return
end

archive = sort_nodes(archive, 'raw');
N = min(N, numel(archive));

csv_dir = fullfile(opts.OUTDIR, 'csv');
if ~isfolder(csv_dir)
    mkdir(csv_dir)
end

fprintf('\n=== EXPORT TOP %d CSV ===\n', N)

for i = 1:N
    node = archive(i);
    sol.sequence = node.seq;
    sol.t_flyby = node.t;
    sol.Lambert_dir = node.dirs;

    seq_tag = strjoin(arrayfun(@num2str, sol.sequence, 'UniformOutput', false), '-');
    outfile = fullfile(csv_dir, sprintf('rank%02d_J%.6f_%s.csv', i, node.J_raw, seq_tag));

    try
        solution_to_csv_patched(sol, outfile);
        fprintf('#%02d wrote %s\n', i, outfile)
    catch ME
        fprintf('#%02d export failed: %s\n', i, ME.message)
    end
end

end

%% =====================================================================
function print_best(nodes, N)

if isempty(nodes)
    fprintf('No nodes.\n')
    return
end

N = min(N, numel(nodes));
for k = 1:N
    fprintf('#%02d raw=%.6f off=%.6f rank=%.6f t=%.2f rate=%.4f seq=[%s]\n', ...
        k, nodes(k).J_raw, nodes(k).J_official, nodes(k).rank, nodes(k).t(end), ...
        nodes(k).J_raw/max(nodes(k).t(end),1e-9), sprintf('%d ', nodes(k).seq))
end

end

%% =====================================================================
function disp_best(node)

if isempty(node)
    fprintf('No best node.\n')
    return
end

fprintf('J_raw      = %.12f\n', node.J_raw)
fprintf('J_official = %.12f\n', node.J_official)
fprintf('rank       = %.12f\n', node.rank)
fprintf('t_end      = %.9f yr\n', node.t(end))
fprintf('score/year = %.9f\n', node.J_raw/max(node.t(end),1e-9))
fprintf('seq        = [%s]\n', sprintf('%d ', node.seq))
fprintf('times      = [%s]\n', sprintf('%.6f ', node.t))
fprintf('dirs       = [%s]\n', sprintf('%d ', node.dirs))

end

%% =====================================================================
function print_sequence_details(node, bodies, mu, ys)

if isempty(node)
    return
end

seq = node.seq;
t = node.t;
dirs = node.dirs;

n = numel(seq);
nleg = n - 1;

VP = zeros(n,3);
for k = 1:n
    s = KM_solver(t(k)*ys, bodies.(sprintf('id_%d',seq(k))));
    VP(k,:) = s(4:6).';
end

vdep = zeros(nleg,3);
varr = zeros(nleg,3);
for leg = 1:nleg
    [vd,va] = leg_vel(seq(leg),seq(leg+1),t(leg),t(leg+1),dirs(leg),bodies,mu,ys);
    vdep(leg,:) = vd(:).';
    varr(leg,:) = va(:).';
end

names = cell(1,n);
for k = 1:n
    names{k} = body_label(seq(k), bodies);
end

fprintf('\nSequence names:\n')
fprintf('%s\n', strjoin(names, ' -> '))

fprintf('\nDetails:\n')
for k = 1:n
    if k == 1
        vinf_in = norm(vdep(1,:) - VP(k,:));
        vinf_out = NaN;
        delta = NaN;
    elseif k <= nleg
        vinf_in_vec = varr(k-1,:) - VP(k,:);
        vinf_out_vec = vdep(k,:) - VP(k,:);
        vinf_in = norm(vinf_in_vec);
        vinf_out = norm(vinf_out_vec);
        delta = turn_angle_deg(vinf_in_vec, vinf_out_vec);
    else
        vinf_in = norm(varr(k-1,:) - VP(k,:));
        vinf_out = NaN;
        delta = NaN;
    end

    if k <= nleg
        tof = t(k+1) - t(k);
    else
        tof = NaN;
    end

    fprintf('%2d | %-12s | t=%9.4f | TOF=%9.4f | vinf_in=%9.4f | vinf_out=%9.4f | turn=%8.3f deg\n', ...
        k, names{k}, t(k), tof, vinf_in, vinf_out, delta)
end

end

%% =====================================================================
function delta = turn_angle_deg(vinf_in, vinf_out)

vin = norm(vinf_in);
vout = norm(vinf_out);

if vin <= 0 || vout <= 0
    delta = NaN;
    return
end

c = dot(vinf_in, vinf_out)/(vin*vout);
c = max(-1, min(1, c));
delta = rad2deg(acos(c));

end

%% =====================================================================
function name = body_label(id, bodies)

key = sprintf('id_%d', id);
if isfield(bodies, key) && isfield(bodies.(key), 'name')
    name = bodies.(key).name;
else
    name = key;
end

end

%% =====================================================================
function [root, paths] = setup_paths(script_dir)
%SETUP_PATHS Locate project folders and add them to the path.
% addpath(..., '-begin') is used so the intended project functions take
% priority over older copies elsewhere on the MATLAB path.

root = find_project_root_relaxed(script_dir);

paths = struct();
paths.script_dir = script_dir;
paths.flyby_dir = fullfile(root, 'flyby_functions');
paths.submission_dir = fullfile(root, 'submission');
paths.submission_utils_dir = fullfile(paths.submission_dir, 'utils');
paths.orbit_calibration_dir = fullfile(root, 'orbit_calibration');
paths.functions_dir = fullfile(root, 'functions');

add_if_dir(paths.flyby_dir)
add_if_dir(paths.submission_dir)
add_if_dir(paths.submission_utils_dir)
add_if_dir(paths.orbit_calibration_dir)
add_if_dir(paths.functions_dir)
add_if_dir(root)
add_if_dir(script_dir)

rehash toolboxcache

end

%% =====================================================================
function add_if_dir(p)
if isfolder(p)
    addpath(p, '-begin')
end
end

%% =====================================================================
function root = find_project_root_relaxed(start_dir)

root = start_dir;
for k = 1:10
    has_flyby = isfolder(fullfile(root,'flyby_functions')) || isfolder(fullfile(root,'functions','flyby_functions'));
    has_submission = isfolder(fullfile(root,'submission')) || isfile(fullfile(root,'solution_to_csv_patched.m'));
    has_bodies = isfile(fullfile(root,'bodies.mat')) || isfile(fullfile(root,'submission','bodies.mat'));

    if has_bodies && (has_flyby || has_submission)
        return
    end

    parent = fileparts(root);
    if strcmp(parent, root)
        break
    end
    root = parent;
end

% Fallback: current script folder.
root = start_dir;

end

%% =====================================================================
function bodies_file = find_bodies_file(root, paths, script_dir)

candidates = {
    fullfile(paths.submission_dir, 'bodies.mat')
    fullfile(paths.flyby_dir, 'bodies.mat')
    fullfile(root, 'bodies.mat')
    fullfile(script_dir, 'bodies.mat')
    };

for i = 1:numel(candidates)
    if isfile(candidates{i})
        bodies_file = candidates{i};
        return
    end
end

error('Missing bodies.mat. Put it near this script or in submission/flyby_functions.')

end
